### ISSUE TITLE
[Hindi QAs] Noticed some questions in the Hindi parts of the data that may not need visual input

### ISSUE THREAD

**Issue by prajdabre** [mbzuai-oryx/ALM-Bench#2]
Hi,

I checked the Hindi section of the dataset and noticed several examples like the following, which do not need any visual cues to answer:

1. Which literary movement is Jaishankar Prasad associated with?
2. Explain the historical and architectural significance of Humayun's Tomb, highlighting its influence on later Mughal architecture and the specific features that make it unique.
3. In which century were the temples of Pattadakal built?

There's also questions like: "Which color is prominent in the rice dish shown in the image?". I wonder if there is anything culture specific that can be tested with such a question. To this end, one should concretely define "what is culture?"

Additionally, the answers to some questions might need fixing to make them look more formal. 

For example: "Is the structure in the image a UNESCO World Heritage Site?": True, it is.
I wonder if "True, it is" can simply be reduced to "True" to make it more formal, succinct and easy to evaluate.

Regards.

**Comment by ashmalvayani** [comment]
Hi, thank you for your comment and the feedback on our work. We have corrected the highlighted concerns in our dataset; we appreciate your effort in the QC of our dataset.

For the definition of culture, we do mention it in our paper:
"Culturally grounded elements representing shared knowledge, values, and objectives among the people in that culture that are collectively understood."
