### ISSUE TITLE
Translation errors in Telugu

### ISSUE THREAD

**Issue by nishkalavallabhi** [mbzuai-oryx/ALM-Bench#3]
I noticed several query translation errors in the Telugu subset. Is there a way to submit edits or flag the rows with wrong translations?

**Comment by ashmalvayani** [comment]
Hi, thanks for showing interest in our work. Please feel free to reach out to me at ashmalanis08@gmail.com with the suggestions/ rows where you think improvements are needed and we'll incorporate your feedback and recheck with our native speakers as well.
